version: "3.7"
services:
  mongo:
    image: mongo:5.0
    container_name: koibanxsmongo
    ports:
      - 27017:27017
    networks:
      - "network"

  mongo_seed:
    container_name: seed
    build: ./mongoseed
    networks:
      - "network"
    depends_on:
      - mongo

volumes:
  db:
    driver: local
networks:
  network:
    name: "koibanxs"
